global:
 message: Welcome to customer service dev environment!!
server:
 port: 8082
message: Hello from dev!!
spring:
 datasource:
  url: jdbc:oracle:thin:@localhost:1521/XEPDB1
  username: SYS AS SYSDBA
  password: 1234
jpa:
 hibernate:
  ddl-auto: update
  show-sql: true
