global:
 message: Welcome to customer service dev environment!!
server:
 port: 8082
message: Hello from dev!!
spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/cust_dev
  username: postgres
  password: 1234
jpa:
 hibernate:
  ddl-auto: update
  show-sql: true
