spring:
  application:
    name: customer-service
datasource:
   url: jdbc:postgresql://localhost:5432/customer-master
   driverClassName: org.postgresql.Driver
jpa:
  hibernate:
    ddl-auto: none
    show-sql: false
