global:
 message: Welcome to customer service dev environment!!
server:
 port: 8082
message: Hello from dev!!
spring:
 datasource:
  url: jdbc:oracle:thin:@localhost:1521/xe
  username: SYS AS SYSDBA
  password: 1234
jpa:
# 1. Hibernate DDL Auto - This creates the table and sequence!
 hibernate:
  ddl-auto: update
# 2. Dialect
  database-platform: org.hibernate.dialect.OracleDialect
    
# 3. Show SQL in the console
show-sql: true
properties:
  hibernate:
    format_sql: true
