global:
 message: Welcome to order service dev environment!!
server:
 port: 8084
message: Hello from order dev!!
spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/order-master
  username: postgres
  password: 1234
jpa:
# 1. Hibernate DDL Auto - This creates the table and sequence!
 hibernate:
  ddl-auto: update
# 2. Dialect
  database-platform: org.hibernate.dialect.OracleDialect
    
# 3. Show SQL in the console
show-sql: true
properties:
  hibernate:
    format_sql: true
      default_schema: order_master
