global:
 message: Welcome to order service production environment!!
server:
 port: 8085
message: Hello from order prod!!
spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/order_prod
  username: postgres
  password: 1234
jpa:
 hibernate:
  ddl-auto: update
  show-sql: true
